### PR TITLE
More Rails-like behavior

### PR DESCRIPTION
**Pull request by vellotis**
Hi @ssowonny 

I have many times seeked the strong-parameters implementation for node. But so fa none of the available ones hasn't fulfilled my needs. The ones currently present doesn't support performing deep permitting. So I implemented one that does support it. It would be nice if I could use your managed npm package name to publish it.

To support nested permitting it is required to have more complex logic than just having proprietary fields that cannot be used as parameter keys (eg. 'permit'). So this has a slightly different API than previous `strongify`.

I didn't know if I should keep the legacy version or not. So I left it there. But updated middlewares to use the new permitter.

A PR or any advice to work towards PR would be wlecome.

Regards

### CODE REVIEW

**Comment by ssowonny** [comment]
Hi @vellotis, thank you so much for your contribution.
It's awesome that you made it to support deep permitting, thank you.

The `strongify` was originally implemented here: https://github.com/xpepermint/koa-strong-params/blob/2a81065064b2a5096dc57545fc611607f122f047/lib/index.js#L17 . I think you can remove the part if the `Parameter` method supports all the functions of `strongify`. It'll be much better if you change the file name also.

I'll review the code as soon as possible.
Best
Sungwon

**Comment by vellotis** [comment]
It doesn't support `except` and `merge` methods. But I didn't see a really solid use case for them. Rails StrongParameters doesn't have them as well. What is your opinion on this?

**Comment by vellotis** [comment]
Should be "good to go" from my side.

**Comment by vellotis** [comment]
ping!

**Comment by ssowonny** [comment]
Oops, sorry for late @vellotis . I'll deploy it today, thanks!

**Pull request merged**
